spring:
  application:
    name: estimator-prototype
  ai:
    google:
      genai:
        api-key: ${GEMINI_KEY:}
        chat:
          options:
            model: gemini-2.5-flash
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://elasticsearch:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:changeme}