spring:
  application:
    name: estimator-prototype
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:0.5b
          think-option:
            enabled: false